// <auto-generated />
using System;
using Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructura.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20190817215858_basePractice")]
    partial class basePractice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Infraestructura.Modelos.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionActividad");

                    b.Property<int>("IdUsuario");

                    b.HasKey("IdActividad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("Infraestructura.Modelos.DetalleActividad", b =>
                {
                    b.Property<int>("IdDetalleActividad")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdActividad");

                    b.Property<DateTime>("fecha");

                    b.Property<int>("tiempo");

                    b.HasKey("IdDetalleActividad");

                    b.HasIndex("IdActividad");

                    b.ToTable("detalleActividades");
                });

            modelBuilder.Entity("Infraestructura.Modelos.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreUsuario");

                    b.Property<string>("Password");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Infraestructura.Modelos.Actividad", b =>
                {
                    b.HasOne("Infraestructura.Modelos.Usuario", "Usuario")
                        .WithMany("Actividades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Infraestructura.Modelos.DetalleActividad", b =>
                {
                    b.HasOne("Infraestructura.Modelos.Actividad", "Actividad")
                        .WithMany("DetalleActividades")
                        .HasForeignKey("IdActividad")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
